In [161]:
import numpy as np
from scipy.spatial.distance import pdist, cdist
A = np.zeros((10,10))

In [2]:
# print("util:")
# for idx, val in np.ndenumerate(A):
#     print(np.array(idx), val)

In [3]:
B = np.array([np.array(x) for (x,y) in np.ndenumerate(A)])
print(B)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [0 6]
 [0 7]
 [0 8]
 [0 9]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [1 6]
 [1 7]
 [1 8]
 [1 9]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [2 8]
 [2 9]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 8]
 [3 9]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]
 [4 6]
 [4 7]
 [4 8]
 [4 9]
 [5 0]
 [5 1]
 [5 2]
 [5 3]
 [5 4]
 [5 5]
 [5 6]
 [5 7]
 [5 8]
 [5 9]
 [6 0]
 [6 1]
 [6 2]
 [6 3]
 [6 4]
 [6 5]
 [6 6]
 [6 7]
 [6 8]
 [6 9]
 [7 0]
 [7 1]
 [7 2]
 [7 3]
 [7 4]
 [7 5]
 [7 6]
 [7 7]
 [7 8]
 [7 9]
 [8 0]
 [8 1]
 [8 2]
 [8 3]
 [8 4]
 [8 5]
 [8 6]
 [8 7]
 [8 8]
 [8 9]
 [9 0]
 [9 1]
 [9 2]
 [9 3]
 [9 4]
 [9 5]
 [9 6]
 [9 7]
 [9 8]
 [9 9]]


In [4]:
C = np.array([i-j for i in B for j in B])
print(C)

[[ 0  0]
 [ 0 -1]
 [ 0 -2]
 ...
 [ 0  2]
 [ 0  1]
 [ 0  0]]


In [5]:
# Compare all the elements between two array
an_array = np.array([[1,2],[3,4]])
another_array = np.array([[1,2],[3,4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True


In [6]:
def test1(a,b):
    return a+b

In [7]:
test1(1,2)

3

In [8]:
def variable_num_of_param(*varvar):
    print(np.array(varvar).reshape(-1).shape)
    

In [9]:
list1 = ['hello', 'hi', 'Nope', 'What?']
variable_num_of_param(list1)

(4,)


In [10]:
A = np.zeros(9).reshape(3,3)
def make_spatial_differnce_matrix(*args):
    img_shape = args[0]
    wid = img_shape[0] * img_shape[1]
    TmpMtx = np.zeros(wid).reshape(img_shape[0],img_shape[1])
    TmpMtx = np.array([np.array(i) for (i,j) in np.ndenumerate(TmpMtx)])
    TmpMtx = np.array([i-j for i in TmpMtx for j in TmpMtx]).reshape(wid,wid,2)
#     print(TmpMtx.shape)
    return TmpMtx
D1 = make_spatial_differnce_matrix(A.shape)
print(D1)

[[[ 0  0]
  [ 0 -1]
  [ 0 -2]
  [-1  0]
  [-1 -1]
  [-1 -2]
  [-2  0]
  [-2 -1]
  [-2 -2]]

 [[ 0  1]
  [ 0  0]
  [ 0 -1]
  [-1  1]
  [-1  0]
  [-1 -1]
  [-2  1]
  [-2  0]
  [-2 -1]]

 [[ 0  2]
  [ 0  1]
  [ 0  0]
  [-1  2]
  [-1  1]
  [-1  0]
  [-2  2]
  [-2  1]
  [-2  0]]

 [[ 1  0]
  [ 1 -1]
  [ 1 -2]
  [ 0  0]
  [ 0 -1]
  [ 0 -2]
  [-1  0]
  [-1 -1]
  [-1 -2]]

 [[ 1  1]
  [ 1  0]
  [ 1 -1]
  [ 0  1]
  [ 0  0]
  [ 0 -1]
  [-1  1]
  [-1  0]
  [-1 -1]]

 [[ 1  2]
  [ 1  1]
  [ 1  0]
  [ 0  2]
  [ 0  1]
  [ 0  0]
  [-1  2]
  [-1  1]
  [-1  0]]

 [[ 2  0]
  [ 2 -1]
  [ 2 -2]
  [ 1  0]
  [ 1 -1]
  [ 1 -2]
  [ 0  0]
  [ 0 -1]
  [ 0 -2]]

 [[ 2  1]
  [ 2  0]
  [ 2 -1]
  [ 1  1]
  [ 1  0]
  [ 1 -1]
  [ 0  1]
  [ 0  0]
  [ 0 -1]]

 [[ 2  2]
  [ 2  1]
  [ 2  0]
  [ 1  2]
  [ 1  1]
  [ 1  0]
  [ 0  2]
  [ 0  1]
  [ 0  0]]]


In [11]:
A = np.zeros(9).reshape(3,3)
#print("A:\n", A,"\n")
B = np.array(list([np.array(x) for (x,y) in np.ndenumerate(A)]))
# print(B)
# print(B.reshape(3,3,2))
D2 = np.array([i-j for i in B for j in B]).reshape(9,9,2)
print(D2)

[[[ 0  0]
  [ 0 -1]
  [ 0 -2]
  [-1  0]
  [-1 -1]
  [-1 -2]
  [-2  0]
  [-2 -1]
  [-2 -2]]

 [[ 0  1]
  [ 0  0]
  [ 0 -1]
  [-1  1]
  [-1  0]
  [-1 -1]
  [-2  1]
  [-2  0]
  [-2 -1]]

 [[ 0  2]
  [ 0  1]
  [ 0  0]
  [-1  2]
  [-1  1]
  [-1  0]
  [-2  2]
  [-2  1]
  [-2  0]]

 [[ 1  0]
  [ 1 -1]
  [ 1 -2]
  [ 0  0]
  [ 0 -1]
  [ 0 -2]
  [-1  0]
  [-1 -1]
  [-1 -2]]

 [[ 1  1]
  [ 1  0]
  [ 1 -1]
  [ 0  1]
  [ 0  0]
  [ 0 -1]
  [-1  1]
  [-1  0]
  [-1 -1]]

 [[ 1  2]
  [ 1  1]
  [ 1  0]
  [ 0  2]
  [ 0  1]
  [ 0  0]
  [-1  2]
  [-1  1]
  [-1  0]]

 [[ 2  0]
  [ 2 -1]
  [ 2 -2]
  [ 1  0]
  [ 1 -1]
  [ 1 -2]
  [ 0  0]
  [ 0 -1]
  [ 0 -2]]

 [[ 2  1]
  [ 2  0]
  [ 2 -1]
  [ 1  1]
  [ 1  0]
  [ 1 -1]
  [ 0  1]
  [ 0  0]
  [ 0 -1]]

 [[ 2  2]
  [ 2  1]
  [ 2  0]
  [ 1  2]
  [ 1  1]
  [ 1  0]
  [ 0  2]
  [ 0  1]
  [ 0  0]]]


In [12]:
def compare_two_matrix(A,B):
#     A = np.array([[1,2],[3,4]])
#     B = np.array([[1,2],[3,4]])

    comparison = A == B
    equal_arrays = comparison.all()

    print(equal_arrays)
compare_two_matrix(D1, D2)

True


In [13]:
D3 = pdist(B)

In [14]:
print(D3)
print(D3.shape)

[1.         2.         1.         1.41421356 2.23606798 2.
 2.23606798 2.82842712 1.         1.41421356 1.         1.41421356
 2.23606798 2.         2.23606798 2.23606798 1.41421356 1.
 2.82842712 2.23606798 2.         1.         2.         1.
 1.41421356 2.23606798 1.         1.41421356 1.         1.41421356
 2.23606798 1.41421356 1.         1.         2.         1.        ]
(36,)


In [15]:
al = np.array((2,3,4,5,8,9,10,14,15,20))
print(al)
print()
n = 5
a = np.zeros((n,n)) # Initialize nxn matrix
triu = np.triu_indices(n, 1) # Find upper right indices of a triangular nxn matrix
tril = np.tril_indices(n, -1) # Find lower left indices of a triangular nxn matrix
a[triu] = al # Assign list values to upper right matrix
a[tril] = a.T[tril] # Make the matrix symmetric

print(a)

[ 2  3  4  5  8  9 10 14 15 20]

[[ 0.  2.  3.  4.  5.]
 [ 2.  0.  8.  9. 10.]
 [ 3.  8.  0. 14. 15.]
 [ 4.  9. 14.  0. 20.]
 [ 5. 10. 15. 20.  0.]]


In [55]:
A = np.arange(24).reshape(4,6)
print(A)
A[1,5] = 2
# print(A[:,2], A[:,4], A[:,5])
print(A[...,2], A[...,4], A[...,5]) # Claim to be faster
print(np.argmax(np.array([A[...,2], A[...,4], A[...,5]]), axis=0))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 2  8 14 20] [ 4 10 16 22] [ 5  2 17 23]
[2 1 2 2]


In [200]:
# Cluster_Label = np.array([0 if pdist(np.append(K[i].reshape(1,10000), Mean_Clus_1, axis=0))[0]<pdist(np.append(K[i].reshape(1,10000), Mean_Clus_2,axis=0))[0] else 1 for i in range(dpts_num)])
A = np.array([[1,12],
              [14,3],
              [11,12],
              [13,15]])
B1 = np.array([[2,3]])
B2 = np.array([[11,12]])
B3 = np.array([[13,14]])
i = 0
M = np.array([[1,2]])
print(A.shape)
print(M.shape)
# np.append(M,A,axis=0)
print(np.array([M[0],A[0]]))
E = cdist(M,A,'euclidean')
print(E)
print(E.shape)
print("hellp")
Cluster_Label = np.array(np.argmax(np.array([A[...,1],A[...,1],A[...,0]]), axis=1))
print(Cluster_Label)

dtb1 = cdist(B1, A)
dtb2 = cdist(B2, A)
dtb3 = cdist(B3, A)

print(dtb1)
print(dtb2)
print(dtb3)

W = np.array([dtb1[0], dtb2[0]])
print(np.concatenate([dtb1, dtb2, dtb3]))
print("hel")
print(np.array([dtb1[0], dtb2[0]]))
print(np.amax(W,0))
print(np.argmax(W,axis=0))

(4, 2)
(1, 2)
[[ 1  2]
 [ 1 12]]
[[10.         13.03840481 14.14213562 17.69180601]]
(1, 4)
hellp
[3 3 1]
[[ 9.05538514 12.         12.72792206 16.2788206 ]]
[[10.          9.48683298  0.          3.60555128]]
[[12.16552506 11.04536102  2.82842712  1.        ]]
[[ 9.05538514 12.         12.72792206 16.2788206 ]
 [10.          9.48683298  0.          3.60555128]
 [12.16552506 11.04536102  2.82842712  1.        ]]
hel
[[ 9.05538514 12.         12.72792206 16.2788206 ]
 [10.          9.48683298  0.          3.60555128]]
[10.         12.         12.72792206 16.2788206 ]
[1 0 0 0]


In [145]:
print(np.array([A[i], B[0]]))
E1 = np.array([A[i], B1[0]])
E2 = np.array([A[i], B2[0]])
E3 = np.array([A[i], B3[0]])
print(pdist(E1)[0],pdist(E2)[0],pdist(E3)[0])
print(max(np.array([pdist(E1),pdist(E2),pdist(E3)])))
# print(E1,E2,E3)
print([pdist(np.array([A[0], B1[0]]))])
print([pdist(np.array([A[1], B1[0]]))])
print([pdist(np.array([A[2], B1[0]]))])

pdist(B1,A )
# print(pdist(np.array([A[i], B1[0]])))

In [147]:
# from random import Random
# X = rand(3,2);
# Y = rand(3,2);
# pdist(X,Y)

In [202]:
import imageio
images = []
for filename in filenames:
    images.append(imageio.imread(filename))
imageio.mimsave('/path/to/movie.gif', images)


ModuleNotFoundError: No module named 'imageio'